### ISSUE TITLE
docker-compose Mac上跑不起来

### ISSUE THREAD

**Issue by acechef** [ZiRunHua/LeapLedger#1]
原因是mysql:8.0.22没有对应的arm镜像，
![image](https://github.com/user-attachments/assets/968e57d1-ec59-4a1d-9327-d8750bd271e8)
可考虑使用mysql:8.0.30
![image](https://github.com/user-attachments/assets/cec99742-9f32-4e75-bcc0-663963bdf940)

**Comment by acechef** [comment]
BTW, develop分支和master分支好像差别很大？

**Comment by ZiRunHua** [comment]
感谢反馈，关于mysql镜像版本，确实是遗漏的一个细节，初步查看8.0.22到8.0.30的更新日志，升级不会带来显著影响，下版本测试确认没问题后会修改镜像版本。

关于分支差异，从提交记录上看`main`和`develop`分支差异确实很大，是因为为了保持`mian`分支的简洁，我使用了`git merge --squash --strategy-option=theirs origin/develop`，实际上`main`上v1.0.0之前的提交都应该被合并为一个提交以保持简洁。

使用`git diff --name-status  origin/main..origin/develop`可以看到差异的文件：
```
A       README.en.md
M       README.md
M       config.yaml
```
这些差异是`main`上config.yaml注释的修改和README的更新，后续会合并到`develop`

**Comment by acechef** [comment]
👌🏻
